<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="restAssuredTestGenerator" nsURI="http://www.example.org/restAssuredTestGenerator"
    nsPrefix="restAssuredTestGenerator">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDefs" upperBound="-1"
        eType="#//ClassDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//Test" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" lowerBound="1"
        eType="#//Request" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validate" lowerBound="1"
        eType="#//Validate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestElements" upperBound="-1"
        eType="#//RequestElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpMethod" eType="#//HttpMethod"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionalPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethod">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="DELETE" value="3"/>
    <eLiterals name="PATCH" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Url" eSuperTypes="#//RequestElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Headers" eSuperTypes="#//RequestElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" lowerBound="1"
        upperBound="-1" eType="#//Header" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryParams" eSuperTypes="#//RequestElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryParams" lowerBound="1"
        upperBound="-1" eType="#//QueryParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="#//RequestElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rawValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Validate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validateElements" lowerBound="1"
        upperBound="-1" eType="#//ValidateElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidateElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatusCode" eSuperTypes="#//ValidateElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseHeaders" eSuperTypes="#//ValidateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" lowerBound="1"
        upperBound="-1" eType="#//Header" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseBody" eSuperTypes="#//ValidateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//ResponseBodyElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseBodyElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BodyContains" eSuperTypes="#//ResponseBodyElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fields" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyExact" eSuperTypes="#//ResponseBodyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pairs" lowerBound="1" upperBound="-1"
        eType="#//BodyExactPair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyExactPair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
